# Generated by Django 4.2.6 on 2023-11-02 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_merch_alter_apraisal_options_alter_apraisal_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='merchen',
            field=models.ManyToManyField(to='main_app.merch'),
        ),
    ]
