# Generated by Django 4.2.6 on 2023-11-03 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_card_merchen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='merchen',
            new_name='merch',
        ),
    ]
