# Generated by Django 4.2.6 on 2023-11-03 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_merchen_card_merch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='merch',
            new_name='merchen',
        ),
    ]
