# Generated by Django 4.2.6 on 2023-11-03 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_card_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apraisal',
            name='card',
        ),
    ]
